apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-stabox
spec:
  selector:
    matchLabels:
      app: mysql-stabox
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-stabox
    spec:
      containers:
        - image: mariadb:10.7.3
          name: mysql-stabox
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: St@b0xPwd
            - name: MARIADB_DATABASE
              value: stabox
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-stabox-pv-claim

