apiVersion: v1
kind: Service
metadata:
  name: mysql-stabox-cluster-ip-service
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      # nodePort: 30008
  selector:
    app: mysql-stabox

