apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-stabox-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-stabox"

