apiVersion: v1
kind: Service
metadata:
  name: stabox-cluster-ip-service
spec:
  type: ClusterIP #NodePort
  ports:
    - port: 80
      targetPort: 3333
      # nodePort: 30007
  selector:
    component: stabox

