name: Create Docker images

on: workflow_dispatch

jobs:
  nestjs-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: . 
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}    
    
    - name: Build the Docker image
      working-directory: .
      run: |
        docker build . --file Dockerfile -t ghcr.io/bognarpal/stabox:${{steps.package-version.outputs.current-version}} -t ghcr.io/bognarpal/stabox:latest 
        docker push ghcr.io/bognarpal/stabox:latest
        docker push ghcr.io/bognarpal/stabox:${{steps.package-version.outputs.current-version}}